# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 022f160d601a33aac400775f59981ef483d1dbf8fb09b19a38a72316f7f6cf784748c282528146191d0550992c95c3d27c9f877e198c4bd1e838010249ea77a6
  secret_google_key: AIzaSyDIfoumG-sqGDBc0LemLU_RJX19EQNZkjA

test:
  secret_key_base: 469b9890e46385977d2ee26004b1d2be09ff4ac31f8c3ec250f0eecbad3a9eed5bf59e9761f8ec14f62d3693b97fb841188b3cb9f50135bf84fb7a35790e65ae
  secret_google_key: AIzaSyDIfoumG-sqGDBc0LemLU_RJX19EQNZkjA

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_google_key: <%= ENV["SECRET_GOOGLE_KEY"] %>
